// Catálogo base de códigos de error (US-093 / BE-001). ADR-API-002; Doc 14 §18.
// Códigos estables consumidos por el frontend, MSW y agentes IA. Los códigos de negocio
// específicos (CURRENCY_IMMUTABLE, QUOTE_LIMIT_REACHED, etc.) los agregan las historias de feature.
export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  // US-094 (PB-P0-004): conflicto específico de email ya registrado (EC-02, NT-02) → 409.
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  // US-095 (PB-P0-004): intento de cambiar `currencyCode` tras crear el evento (AC-05, NT-08) → 409.
  CURRENCY_IMMUTABLE: 'CURRENCY_IMMUTABLE',
  // US-096 (PB-P0-004): límites/estado del flujo Quote/Booking (AC-01, EC-04/05/07).
  MAX_QUOTE_REQUESTS_EXCEEDED: 'MAX_QUOTE_REQUESTS_EXCEEDED', // 409
  DUPLICATE_QUOTE_REQUEST_ACTIVE: 'DUPLICATE_QUOTE_REQUEST_ACTIVE', // 409
  QUOTE_EXPIRED: 'QUOTE_EXPIRED', // 410
  BUSINESS_RULE_VIOLATION: 'BUSINESS_RULE_VIOLATION',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  // US-097 (PB-P0-004): contrato AI endpoints (Doc 16 §Error Handling).
  MISSING_INPUT: 'MISSING_INPUT', // 400
  UNSUPPORTED_LANGUAGE: 'UNSUPPORTED_LANGUAGE', // 422
  AI_INVALID_OUTPUT: 'AI_INVALID_OUTPUT', // 422
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION', // 422
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE', // 503
  PERSISTENCE_ERROR: 'PERSISTENCE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  // Retenido del bootstrap US-091 para 400 de captcha / upload (no es VALIDATION_ERROR).
  BAD_REQUEST: 'BAD_REQUEST',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
